apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-web
spec:
  # replicas: 3
  selector:
    matchLabels:
      app: synergychat-web
  template:
    metadata:
      labels:
        app: synergychat-web
    spec:
      containers:
      - name: synergychat-web
        image: bootdotdev/synergychat-web:latest
        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "50m"
        envFrom:
        - configMapRef:
            name: synergychat-web-configmap
        ports:
        - containerPort: 8080
